##
##
## make libs
## (C) 2006 Teo Fonrouge <teo@windtelsoft.com>
##
##

XHF_DEBUG=

MODULE=wxlib

PRGS = \
wxharbour.cpp \
wx_app.cpp \
wx_boxsizer.cpp \
wx_browse.cpp \
wx_button.cpp \
wx_dialog.cpp \
wx_evthandler.cpp \
wx_frame.cpp \
wx_grid.cpp \
wx_gridtablebase.cpp \
wx_menubar.cpp \
wx_menu.cpp \
wx_menuitem.cpp \
wx_sizer.cpp \
wx_statusbar.cpp \
wx_textctrl.cpp \
wx_toplevelwindow.cpp \
wx_object.cpp \
wx_validator.cpp \
wx_window.cpp \
wxhapp.prg \
wxhboxsizer.prg \
wxhbrowse.prg \
wxhbutton.prg \
wxhcolumn.prg \
wxhcontrol.prg \
wxhdialog.prg \
wxhevthandler.prg \
wxhframe.prg \
wxhgrid.prg \
wxhgridtablebase.prg \
wxhmenubar.prg \
wxhmenuitem.prg \
wxhmenu.prg \
wxhobject.prg \
wxhsizer.prg \
wxhstatusbar.prg \
wxhtextctrl.prg \
wxhtoplevelwindow.prg \
wxhvalidator.prg \
wxhwindow.prg

#PATHOBJ = ../obj/gcc
#PATHCXXPRG = ../cxxprg/gcc

include ../config/Makefile.inc
