##
##
## (C) 2006 Teo Fonrouge <teo@windtelsoft.com>
##
##

XHF_DEBUG=-b

MODULE = helloworld1

PRGS = \
       helloworld1.prg

PATHOBJ = obj/gcc
PATHCXXPRG = cxxprg/gcc
EXENAME = helloworld1

include ../../config/Makefile.inc

include ../../config/Makefile.run
