##
##
## (C) 2006 Teo Fonrouge <teo@windtelsoft.com>
##
##

XHF_DEBUG=

MODULE = helloworld

PRGS = \
       helloworld.prg

PATHOBJ = obj/gcc
PATHCXXPRG = cxxprg/gcc
EXENAME = helloworld.exe

include ../../config/Makefile.inc

include ../../config/Makefile.run
