##
##
## (C) 2006 Teo Fonrouge <teo@windtelsoft.com>
##
##

XHF_DEBUG=-b

MODULE = dbbrowser

PRGS = \
       dbbrowser.prg

PATHOBJ = obj/gcc
PATHCXXPRG = cxxprg/gcc
EXENAME = dbbrowser

include ../../config/Makefile.inc

include ../../config/Makefile.run
